title = 'Ruido, Error, Comunicación'
file_name = 'r-e-c'
description = '¿Qué nos enseña el ruido y el error?'
tags = []
posted = '23/04/2023'
estimated_reading_time = 13
author = 'Roberto' # feel free to swap with your own name
order = 1